set_property SRC_FILE_INFO {cfile:/media/mkdigitals/d/projects/core-v-mcu/build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.gen/sources_1/ip/xilinx_clk_mngr/xilinx_clk_mngr.xdc rfile:../build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.gen/sources_1/ip/xilinx_clk_mngr/xilinx_clk_mngr.xdc id:1 order:EARLY scoped_inst:i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_clk_manager/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/media/mkdigitals/d/projects/core-v-mcu/build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.gen/sources_1/ip/xilinx_eth_clk_mngr/xilinx_eth_clk_mngr.xdc rfile:../build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.gen/sources_1/ip/xilinx_eth_clk_mngr/xilinx_eth_clk_mngr.xdc id:2 order:EARLY scoped_inst:i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_eth_clk_manager/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/media/mkdigitals/d/projects/core-v-mcu/build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.srcs/constrs_1/new/core-v-mcu-debug.xdc rfile:../build/openhwgroup.org_systems_core-v-mcu_0/nexys-a7-100t-vivado/openhwgroup.org_systems_core-v-mcu_0.srcs/constrs_1/new/core-v-mcu-debug.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:4 order:LATE scoped_inst:{i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/rx_buffer_i/dc_fifo_rx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:5 order:LATE scoped_inst:{i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/tx_buffer_i/dc_fifo_tx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:{i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/rx_buffer_i/dc_fifo_rx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../opt/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:{i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/tx_buffer_i/dc_fifo_tx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst} unmanaged:yes} [current_design]
current_instance i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_clk_manager/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.050
current_instance
current_instance i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_eth_clk_manager/inst
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.050
current_instance
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_eth_clk_manager/inst/clk_out1]]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 26 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[0]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[1]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[2]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[3]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[4]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[5]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[6]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[7]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[8]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[9]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[10]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[11]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[12]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[13]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[14]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[15]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[16]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[17]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[18]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[19]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[20]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[21]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[22]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[23]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[24]} {i_core_v_mcu/i_soc_domain/clk_check/eth_clk_cnt_reg[25]}]]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list i_core_v_mcu/i_soc_domain/clk_check/ld_eth_clk_blink]]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_clk_manager/inst/clk_out1]]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[0]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[1]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[2]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[3]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[4]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[5]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[6]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[7]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[8]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[9]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[10]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[11]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[12]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[13]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[14]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[15]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[16]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[17]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[18]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[19]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[20]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[21]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[22]} {i_core_v_mcu/i_soc_domain/clk_check/ref_clk_cnt_reg[23]}]]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list i_core_v_mcu/i_soc_domain/clk_check/ld_ref_clk_blink]]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list i_sysclk_iobuf_n_0]]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_clk_manager/locked]]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list i_core_v_mcu/i_soc_domain/i_clk_rst_gen/clk_gen_i/i_eth_clk_manager/locked]]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets i_sysclk_iobuf_n_0]
current_instance {i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/rx_buffer_i/dc_fifo_rx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:4 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/tx_buffer_i/dc_fifo_tx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:5 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/rx_buffer_i/dc_fifo_rx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {i_core_v_mcu/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0].i_ethernet/tx_buffer_i/dc_fifo_tx/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
