vcd file eth.vcd
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0]/i_ethernet/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0]/i_ethernet/u_reg_if/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0]/i_ethernet/u_eth_tx_ctrl/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0]/i_ethernet/u_eth_rx_ctrl/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0]/i_ethernet/rx_buffer_i/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_eth_gen[0]/i_ethernet/tx_buffer_i/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_uart_gen[0]/i_uart/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/i_uart_gen[1]/i_uart/*
vcd add sim:core_v_mcu_tb/core_v_mcu_i/i_soc_domain/soc_peripherals_i/i_udma/*clk*